In [7]:
# Источники вдохновения #
# BackProp #
    # https://neurohive.io/ru/osnovy-data-science/obratnoe-rasprostranenie/
# Нейроны, ф-ии активации и суммирования #
    # https://stepik.org/lesson/24679/step/4?unit=7041
# Примеры #
    # https://neurohive.io/ru/tutorial/kak-sozdat-nejronnuju-set-s-nulja-na-jazyke-python/
    # https://python-scripts.com/intro-to-neural-networks
# Код из 1-го примера #
    #https://gist.github.com/jamesloyys/ff7a7bb1540384f709856f9cdcdee70d#file-neural_network_backprop-py

In [1]:
# библиотеки и входные данные #
import numpy as np

# РАБОТАЕТ!!! #

# тест #
# на выходе 0, если 0 > 1 #
# на выходе 1, если 1 > 0 #
x = np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,0]), dtype=float)
y = np.array(([0],[1],[1],[1]), dtype=float)


In [2]:
# Функция активации #
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [3]:
# Производная ф-ии активации #
def sigmoid_d(x):
    fx = sigmoid(x)
    return fx * (1 - fx)

In [4]:
# Класс нейронки #
class NeuralNetwork:
    def __init__(self, x, y, n1_count, n2_count):
        # Веса #
        # 1 - кол-во входов, 2 - кол-во нейронов #
        self.w1 = np.random.rand(3, n1_count) # Веса первого слоя #
        self.w2 = np.random.rand(n1_count, n2_count) # Веса второго слоя #
        
        self.w_out = np.random.rand(n2_count, 1) # Веса выходного слоя #
        
        self. y     = y
        self.input  = x
        self.output = np.zeros(y.shape)
        
    def FeedForward(self):
        self.k1    = sigmoid(np.dot(self.input, self.w1))
        self.k2    = sigmoid(np.dot(self.k1, self.w2))
        
        #print('k1 - ' + str(self.k1))
        #print('k2 - ' + str(self.k2))

        self.k_out = sigmoid(np.dot(self.k2, self.w_out))
        
        return self.k_out
        
    def BackProp(self):
        # Упрощения #
        d_pred  = 2 * (self.y - self.k_out) # Это не точно! #
        d_out    = d_pred * sigmoid_d(self.output) # Для выходного слоя #
        
        # Тут могут быть ошибки #
        d_w_out = np.dot(self.k2.T, d_out)
        
        d_w2 = np.dot(self.k1.T, np.dot(d_out, self.w_out.T)*sigmoid_d(self.k2))
        d_w1 = np.dot(self.input.T, np.dot(np.dot(d_out, self.w_out.T)*sigmoid_d(self.k2), self.w2.T)*sigmoid_d(self.k1))
        
        #d_w_out = np.dot(self.k2.T, (2*(self.y-self.k_out)*sigmoid_d(self.output)))
        
        #d_w2    = np.dot(self.k1.T, np.dot(2*(self.y-self.k_out)*sigmoid_d(self.output), self.w_out.T)*sigmoid_d(self.k2))
        #d_w1    = np.dot(self.input.T, np.dot())
        
        
        # Обновление весов #
        self.w1    += d_w1
        self.w2    += d_w2
        self.w_out += d_w_out
        
    def train(self, x, y):
        self.output = self.FeedForward()
        self.BackProp()

In [6]:
# Кол-во нейронов в скрытых слоях #
n1_count = int(input("Укажите кол-во нейронов в 1-м слое: "))
n2_count = int(input("Укажите кол-во нейронов во 2-м слое: "))

# Ограничение, ну так, просто #
if n1_count <= 0:
    n1_count = 1
    
if n2_count <= 0:
    n2_count = 1
    
if n1_count > 10:
    n1_count = 9

if n2_count > 10:
    n2_count = 9

# Объявление класса #
nn = NeuralNetwork(x, y, n1_count, n2_count)

# Тренировка #
for i in range(3000):
    if i % 500 == 0:
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(x))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(nn.FeedForward()))
        print ("Loss: \n" + str(np.mean(np.square(y - nn.FeedForward())))) # mean sum squared loss
        print ("\n")
    nn.train(x, y)

Укажите кол-во нейронов в 1-м слое: 2
Укажите кол-во нейронов во 2-м слое: 4
for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.83310197]
 [0.84269946]
 [0.84206923]
 [0.84496169]]
Loss: 
0.19194533851230614


for iteration # 500

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.15066843]
 [0.93685023]
 [0.93698045]
 [0.99757267]]
Loss: 
0.007666556178575759


for iteration # 1000

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.02202495]
 [0.99092747]
 [0.99093255]
 [0.99911332]]
Loss: 
0.00016260349613471663


for iteration # 1500

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.01110374]
 [0.99549964]
 [0.99550092]
 [0.99935674]]
Loss: 
4.1050449489542546e-05


for iteration # 