In [30]:
# библиотеки и входные данные #
import numpy as np

x = np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
y = np.array(([0],[1],[1],[0]), dtype=float)

In [31]:
# Функция активации #
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [32]:
# Производная ф-ии активации #
def sigmoid_d(x):
    fx = sigmoid(x)
    return fx * (1 - fx)

In [40]:
# Класс нейронки #
class NeuralNetwork:
    def __init__(self, x, y):
        # Веса #
        self.w11 = np.random.rand(3, 4) # Веса первого нейрона #
        self.w12 = np.random.rand(3, 4) # Веса второго нейрона #
        
        self.w_out = np.random.rand(4, 1) # Веса выходного слоя #
        
        self. y     = y
        self.input  = x
        self.output = np.zeros(y.shape)
        
    def FeedForward(self):
        self.k11   = sigmoid(np.dot(self.input, self.w11))
        self.k12   = sigmoid(np.dot(self.input, self.w12))
        # Ошибка, скорее всего здесь #
        self.k_sum = sigmoid(np.dot(self.k11, self.k12))
        #self.k_sum = sigmoid(self.k11 + self.k12)
        self.k_out = sigmoid(np.dot(self.k_sum, self.w_out))
        
        return self.k_out
        
    def BackProp(self):
        d_pred  = 2 * (self.y - self.k_out) # Это не точно! #
        d_out   = d_pred*sigmoid_d(self.output)
        #d_k_sum = sigmoid_d(self.k_sum)
        
        # Тут могут быть ошибки #
        d_w_out = np.dot(self.k_sum.T, d_out) 
        
        d_w11   = np.dot(self.input.T, np.dot(d_out, self.w_out.T)*sigmoid_d(self.k11))
        d_w12   = np.dot(self.input.T, np.dot(d_out, self.w_out.T)*sigmoid_d(self.k12))
        
        # Обновление весов #
        self.w11 += d_w11
        self.w12 += d_w12
        
    def train(self, x, y):
        self.output = self.FeedForward()
        self.BackProp()

In [41]:
# Объявление класса #
nn = NeuralNetwork(x, y)

# Тренировка #
for i in range(1500):
    if i % 100 == 0:
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(x))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(nn.FeedForward()))
        print ("Loss: \n" + str(np.mean(np.square(y - nn.FeedForward())))) # mean sum squared loss
        print ("\n")
    nn.train(x, y)

for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.79496231]
 [0.80368864]
 [0.80356522]
 [0.80865085]]
Loss: 
0.3407515101937473


for iteration # 100

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.69062058]
 [0.69073164]
 [0.69069189]
 [0.69081168]]
Loss: 
0.28637399857840073


for iteration # 200

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.69034838]
 [0.69045344]
 [0.69042057]
 [0.69051374]]
Loss: 
0.28626215115813375


for iteration # 300

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.69025095]
 [0.69032608]
 [0.69029727]
 [0.69036915]]
Loss: 
0.2862174153334712


for iteration # 400

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1